name: SonarCloud C/C++ Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install build-wrapper
      run: |
        wget https://binaries.sonarsource.com/BuildWrapper/build-wrapper-linux-x86.zip
        unzip build-wrapper-linux-x86.zip -d build-wrapper
        chmod +x build-wrapper/build-wrapper-linux-x86/build-wrapper-linux-x86

    - name: Build with Build Wrapper
      run: |
        mkdir -p build_wrapper_output
        ./build-wrapper/build-wrapper-linux-x86/build-wrapper-linux-x86 --out-dir build_wrapper_output make build

    - name: Run SonarCloud analysis
      uses: SonarSource/sonarqube-scan-action@v4
      with:
        args: >
          -Dsonar.projectKey=antonioborrelli11-coder_codice_18
          -Dsonar.organization=antonioborrelli11-coder
          -Dsonar.sources=.
          -Dsonar.cfamily.build-wrapper-output=build_wrapper_output
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
