name: SonarCloud C/C++ Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download Build Wrapper
        run: |
          wget https://binaries.sonarsource.com/BuildWrapper/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86

      - name: Compile with Build Wrapper
        run: |
          ./build-wrapper-linux-x86/build-wrapper-linux-x86 --out-dir build_wrapper_output make clean all

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=antonioborrelli11-coder_codice_18
            -Dsonar.organization=antonioborrelli11-coder
            -Dsonar.cfamily.build-wrapper-output=build_wrapper_output
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
